// Products´schema action types
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'; // Put REST COMMAND AFTER PURCHASE
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING'; // FETCH FROM SERVER
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED'; // ERROR IN FETCHING FROM SERVER
export const ADD_PRODUCTS = 'ADD_PRODUCTS'; // ERROR IN FETCHING FROM SERVER


// Employees´schema action types
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE'; // Put REST COMMAND AFTER PURCHASE
export const EMPLOYEES_LOADING = 'EMPLOYEES_LOADING'; // FETCH FROM SERVER
export const EMPLOYEES_FAILED = 'EMPLOYEES_FAILED'; // ERROR IN FETCHING FROM SERVER
export const ADD_EMPLOYEES = 'ADD_EMPLOYEES'; // ERROR IN FETCHING FROM SERVER

// Purchase´s shema action types
export const ADD_PURCHASE = 'ADD_PURCHASE'; // Push REST COMMAND AFTER PURCHASE
export const PURCHASES_LOADING = 'PURCHASES_LOADING'; // FETCH FROM SERVER
export const PURCHASES_FAILED = 'PURCHASES_FAILED'; // ERROR IN FETCHING FROM SERVER
export const ADD_PURCHASES = 'ADD_PURCHASES'; // Fetch from server

// User register and logout action types

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const USER_LOGOUT = 'USER_LOGOUT';
